include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DropbearSwitch
DropbearSwitch_FILES = BJDropbearSwitch.m
DropbearSwitch_LIBRARIES = flipswitch
DropbearSwitch_CFLAGS = -fobjc-arc
DropbearSwitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
